name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, mac-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: sudo apt install libfontconfig1-dev
    - name: Build
      run: cargo build --verbose
    - name: Build TUI
      run: cargo build --example tui
    - name: Build GUI
      run: cargo build --example gui
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
