name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo check --verbose

  ci_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            INSTALL_DEPS: 
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name:  Install
      run:   |
         if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install -yq libfontconfig1-dev
         elif [ "$RUNNER_OS" == "macOS" ]; then
              : # Do nothing
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi
      shell: bash
    - name: Build
      run: cargo build --verbose
    - name: Build TUI
      run: cargo build --example tui
    - name: Build GUI
      run: cargo build --example gui
    - name: Run tests
      run: cargo test --verbose

  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name:  Install
      run:  sudo apt-get install -yq libfontconfig1-dev
    - uses: boa-dev/criterion-compare-action@v3
      with:
        branchName: ${{ github.base_ref }}


