name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: sudo apt install libfontconfig1-dev
    - name: Build
      run: cargo build --verbose
    - name: Build TUI
      run: cargo build --example tui

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose

  bench:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run benchmark
        run: cargo bench
